In [1]:
file_obj = open('C:\Users\hp\Documents\sentences.txt')
data_list = list(file_obj)

In [2]:
print data_list[0]

In comparison to dogs, cats have not undergone major changes during the domestication process.



In [3]:
print data_list[0].lower()

in comparison to dogs, cats have not undergone major changes during the domestication process.



In [4]:
dl = []
for line in data_list: dl.append(line.lower())

In [5]:
print dl[0]

in comparison to dogs, cats have not undergone major changes during the domestication process.



In [6]:
import re

In [7]:
splitted = []
for line in dl: splitted.append(re.split('[^a-z]',line))
print splitted[0:3]

[['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', ''], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', ''], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', '']]


In [8]:
len(splitted)

22

In [9]:
range(len(splitted))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [10]:
res = []
for i in range(len(splitted)):
    for j in range(len(splitted[i])):
        if splitted[i][j] != '': res.append(splitted[i][j])
res[0:10]
len(res)

484

In [11]:
res_set = set(res)
print(res_set)

set(['displays', 'osx', 'selection', 'safari', 'just', 'developed', 'over', 'vermin', 'domestic', 'named', 'installed', 'symbols', 'through', 'human', 'world', 'disk', 'its', 'fifth', 'features', 'tamed', 'upgrade', 'lb', 'drive', 'to', 'won', 'deliberately', 'marks', 'has', 'predecessor', 'non', 'which', 'read', 'october', 'every', 'os', 'they', 'not', 'during', 'now', 'possess', 'intel', 'keyboards', 'bytes', 'unnecessary', 'patch', 'predators', 'small', 'output', 'entirely', 'where', 'ears', 'available', 'on', 'often', 'sequence', 'some', 'lion', 'frequency', 'are', 'year', 'download', 'terms', 'concern', 'error', 'for', 'pipes', 'since', 'factory', 'artificial', 'content', 'version', 'run', 'between', 'new', 'learned', 'three', 'piped', 'common', 'concatenate', 'be', 'weighing', 'genes', 'use', 'standard', 'release', 'diploid', 'members', 'x', 'based', 'safer', 'by', 'both', 'commands', 'installation', 'installs', 'of', 'needing', 'allows', 'according', 'july', 'later', 'mac', 's',

In [12]:
len(res_set)

254

In [13]:
ress = list(res_set)
print(ress[0])

displays


In [14]:
res_dict = dict()
for i in range(len(ress)):
    res_dict[i] = ress[i]
print(res_dict[0])

displays


In [15]:
import numpy as np

In [16]:
matrix = np.zeros((len(splitted),len(res_set)))

In [17]:
splitted[0].count('in')

1

In [18]:
for i in range(len(splitted)):
    for j in range(len(res_set)):
        matrix[i,j] = splitted[i].count(res_dict[j])
print(matrix)
    

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 2. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [20]:
from scipy.spatial import distance
dist = [0]
for i in range(1,len(splitted)):
    dist.append(distance.cosine(matrix[0],matrix[i]))
    print(dist[i])   

0.9527544408738466
0.8644738145642124
0.8951715163278082
0.7770887149698589
0.9402385695332803
0.7327387580875756
0.9258750683338899
0.8842724875284311
0.9055088817476932
0.8328165362273942
0.8804771390665607
0.8396432548525454
0.8703592552895671
0.8740118423302576
0.9442721787424647
0.8406361854220809
0.956644501523794
0.9442721787424647
0.8885443574849294
0.8427572744917122
0.8250364469440588


In [24]:
a1 = dist.index(min(dist[1:]))
a1     

6

In [25]:
dist[a1] = 1
a2 = dist.index(min(dist[1:]))
a2

4

In [26]:
file_obj.close()

In [29]:
string = str(a1) + ' ' + str(a2)
string

'6 4'

In [30]:
file_obj = open('submission1.txt', 'w')
file_obj.write(string)
file_obj.close()

In [31]:
file_obj = open('submission1.txt', 'w')
file_obj.write(string)
file_obj.close()

6 4
